local c=require("controls").new()
local a,b={},{}
assert(c:update(a,true,2,1.5,true)==nil)
assert(c:update(a,false,0,1.5,true)==nil)
assert(c:update(a,true,0.2,1.5,true)==nil)
assert(c:update(a,false,0,1.5,true)=="dismiss")
assert(c:update(b,true,2,1.5,true)==nil)
assert(c:update(b,false,0,1.5,true)==nil)
assert(c:update(b,true,1.5,1.5,true)=="restart")
assert(c:update(b,true,2,1.5,true)==nil)
assert(c:update(b,false,0,1.5,true)==nil)
assert(c:update(nil,true,2,1.5,true)==nil)
print("controls: tap, hold, fresh press, expiry and one-shot passed")

local c2=require("controls").new()
local t={}
c2:update(t,false,0,3,true,0.3)
c2:update(t,true,1.2,3,true,0.3)
assert(c2:update(t,false,0,3,true,0.3)==nil,"aborted hold dismissed")
c2:update(t,true,2.5,3,true,0.3)
assert(c2:update(t,false,0,3,true,0.3)==nil,"second aborted hold dismissed")
c2:update(t,true,0.1,3,true,0.3)
assert(c2:update(t,false,0,3,true,0.3)=="dismiss","quick tap stopped working")
c2:update(t,true,3,3,true,0.3)
assert(c2.fired,"restart after cancelled holds failed")
